Create #704_Binary_Search.py
ashizawaN/LeetCode pull request #2
Opened 2022-10-14 05:39 UTC by ashizawaN

Closes #1

2022-10-14 07:22 UTC, nayuta-ai requested changes

2022-10-14 07:22 UTC, nayuta-ai commented on #704_Binary_Search.py
> +            m = (left + right) // 2
Rewrite it as follows. 
```mid = (left+right) // 2```

※ Reference
https://pep8-ja.readthedocs.io/ja/latest/#section-14

2022-10-14 07:22 UTC, nayuta-ai commented on #704_Binary_Search.py
> +    def search(self, nums: List[int], target: int) -> int:
Import the List module because it is not a built-in module.

2022-10-14 08:40 UTC, ashizawaN commented on #704_Binary_Search.py
> +    def search(self, nums: List[int], target: int) -> int:
@nayuta-ai 
I posted the code that I submitted to LeetCode. Is this code not enough? Actually, I don't understand enough how to import a module and what is need it for.
Could you give me some hints or something helpful?

2022-10-14 08:48 UTC, nayuta-ai commented on #704_Binary_Search.py
> +    def search(self, nums: List[int], target: int) -> int:
Trying to execute from your local environment makes you understand the issue. 

* Reference: https://docs.python.org/3.8/library/typing.html

2022-10-15 12:13 UTC, nayuta-ai requested changes

2022-10-15 12:13 UTC, nayuta-ai commented on #704_Binary_Search.py
> +from typing import List
Expect two blank lines between imports and class.

2022-10-15 12:13 UTC, nayuta-ai commented on #704_Binary_Search.py
> +            m = (left+right) // 2
"m" is an incomprehensible variable name.
Change from "m" to "mid".

2022-10-16 09:22 UTC, nayuta-ai approved these changes

2022-10-16 11:12 UTC, merged