Create #1351_Count_Negative_Numbers_in_a_Sorted_Matrix.py
ashizawaN/LeetCode pull request #4
Opened 2022-10-14 06:34 UTC by ashizawaN

Closes #3

2022-10-14 07:29 UTC, nayuta-ai requested changes

2022-10-14 07:29 UTC, nayuta-ai commented on #1351_Count_Negative_Numbers_in_a_Sorted_Matrix.py
> +                if grid[i][j]<0:
if grid[i][j] < 0:

2022-10-14 07:29 UTC, nayuta-ai commented on #1351_Count_Negative_Numbers_in_a_Sorted_Matrix.py
> +class Solution:
Rewrite it by using binary search.

2022-10-15 07:18 UTC, ashizawaN commented on #1351_Count_Negative_Numbers_in_a_Sorted_Matrix.py
> +class Solution:
I rewote code with binary search. The test was passed, but when I submitted it, I got the following error. Could you give me some hints to revise it?

## Error

```
Runtime Error Message:
IndexError: list index out of range
    if num[m] < 0:
Line 11 in BinarySearch (Solution.py)
    count += BinarySearch(x)
Line 21 in countNegatives (Solution.py)
    ret = Solution().countNegatives(param_1)
Line 41 in _driver (Solution.py)
    _driver()
Line 52 in <module> (Solution.py)
```

## Code
```
from typing import List

class Solution:
    def countNegatives(self, grid: List[List[int]]) -> int:    
        def BinarySearch(num):
            left = 0
            right = len(num)
        
            while left <= right:
                m = (left+right) // 2
                if num[m] < 0:
                    right = m - 1
                elif num[m] > 0:
                    left = m + 1
                else:
                    return m
            return left
        
        count = 0
        for x in grid:
            count += BinarySearch(x)
        return count
```

2022-10-17 05:29 UTC, nayuta-ai requested changes

2022-10-17 05:29 UTC, nayuta-ai commented on #1351_Count_Negative_Numbers_in_a_Sorted_Matrix.py
>          def BinarySearch(num):
Use snake-case for naming methods.

2022-10-17 06:17 UTC, nayuta-ai approved these changes

2022-10-17 06:58 UTC, merged