Create #2160-3_Minimum_Sum_of_Four_Digit_Number_After_Splitting_Digits.py
ashizawaN/LeetCode pull request #48
Opened 2022-10-23 07:18 UTC by ashizawaN

Closes #45 
with merge sorting

2022-10-23 13:59 UTC, nayuta-ai requested changes
If you want to practice merge sorting, you can search for the "Divide and Conquer" tag.
912. Sort an Array

2022-10-23 13:59 UTC, nayuta-ai commented on #2160-3_Minimum_Sum_of_Four_Digit_Number_After_Splitting_Digits.py
> +        def merge_sort(arr):
Add type annotation

2022-10-23 13:59 UTC, nayuta-ai commented on #2160-3_Minimum_Sum_of_Four_Digit_Number_After_Splitting_Digits.py
> +
E303 too many blank lines (2)

2022-10-23 13:59 UTC, nayuta-ai commented on #2160-3_Minimum_Sum_of_Four_Digit_Number_After_Splitting_Digits.py
> +        def merge(left, right):
Add type annotation

2022-10-24 05:36 UTC, nayuta-ai requested changes

2022-10-24 05:36 UTC, nayuta-ai commented on #2160-3_Minimum_Sum_of_Four_Digit_Number_After_Splitting_Digits.py
> +                return arr
add one blank line

2022-10-24 05:36 UTC, nayuta-ai commented on #2160-3_Minimum_Sum_of_Four_Digit_Number_After_Splitting_Digits.py
> +            left = merge_sort(left)
It doesn't recommend using a same variable name for a different type.

2022-10-31 09:50 UTC, nayuta-ai commented on #2160-3_Minimum_Sum_of_Four_Digit_Number_After_Splitting_Digits.py
> +                return arr
Not modified.

2022-11-01 03:56 UTC, ashizawaN commented on #2160-3_Minimum_Sum_of_Four_Digit_Number_After_Splitting_Digits.py
> +                return arr
Where should I add blank? I installed PEP 8 in VScode, and I used it. But I did't have any errors in the writing rule.

2022-11-02 16:00 UTC, nayuta-ai approved these changes

2022-11-02 16:00 UTC, nayuta-ai commented on #2160-3_Minimum_Sum_of_Four_Digit_Number_After_Splitting_Digits.py
> +                return arr
```
if len(arr) <= 1:
    return arr

mid = len(arr) // 2
```
But, it is not necessary to change because PEP8 doesn't mention it.

BTW, the below document describes this point.
https://docs.google.com/document/d/1jF6-EAnqyM3_-Yj2-efFiJx4eeuBaC00zEzvR3daTTw/edit?usp=sharing

2022-11-02 16:00 UTC, nayuta-ai commented on #2160-3_Minimum_Sum_of_Four_Digit_Number_After_Splitting_Digits.py
> +                return arr
If you can add anything I have pointed out and the document does not describe, please do so as appropriate.

2022-11-03 02:50 UTC, merged