create #1464-1_Maximum_Product_of_Two_Elements_in_an_Array.py
ashizawaN/LeetCode pull request #58
Opened 2022-10-29 11:45 UTC by ashizawaN

Closes #55 
with heapq and error handling

Please check my code.

2022-10-31 09:15 UTC, nayuta-ai requested changes

2022-10-31 09:15 UTC, nayuta-ai commented on #1464-1_Maximum_Product_of_Two_Elements_in_an_Array.py
> +        heapq.heapify(heap)
It is meaningless processing.

2022-10-31 09:15 UTC, nayuta-ai commented on #1464-1_Maximum_Product_of_Two_Elements_in_an_Array.py
> +    def maxProduct(self, nums: List[int]) -> int:
Maybe this solution's time complexity is O(n) because the length of "heap" must be 2 or less and O(2log2) != O(log n).

2022-10-31 09:15 UTC, nayuta-ai commented on #1464-1_Maximum_Product_of_Two_Elements_in_an_Array.py
> +import heapq
import heapq
from typing import List

2022-10-31 09:15 UTC, nayuta-ai commented on #1464-1_Maximum_Product_of_Two_Elements_in_an_Array.py
> +        for i in range (len(nums)-1):
You should check if a type of a value in nums is an integer.

2022-11-01 02:49 UTC, ashizawaN commented on #1464-1_Maximum_Product_of_Two_Elements_in_an_Array.py
> +    def maxProduct(self, nums: List[int]) -> int:
Thank you for pointing that out. I understood that.

2022-11-07 16:53 UTC, nayuta-ai requested changes

2022-11-07 16:53 UTC, nayuta-ai commented on #1464-1_Maximum_Product_of_Two_Elements_in_an_Array.py
> +        for i in range (len(nums)-1):
```
for i in range(len(nums)-1):
```

2022-11-07 16:53 UTC, nayuta-ai commented on #1464-1_Maximum_Product_of_Two_Elements_in_an_Array.py
> +            if type(nums[i]) != "int":
Replace lines 15-18 with the below codes.
```
if type(nums[i]) != "int":
    raise TypeError("The type of a value in nums should be integer.")
```

2022-11-07 16:53 UTC, nayuta-ai commented on #1464-1_Maximum_Product_of_Two_Elements_in_an_Array.py
> +        for i in range (len(nums)-1):
Lines22-23 should be done inside the loop on line 14.

2022-11-10 02:56 UTC, ashizawaN commented on #1464-1_Maximum_Product_of_Two_Elements_in_an_Array.py
> +        assert type(nums) == list, "The type of nums should be list."
@nayuta-ai 
Thank you for your teaching. I understood an assert, raise and try statement. BTW, I don't see any problem with using raise and assert statements in this code, is that correct?

2022-11-10 03:00 UTC, nayuta-ai commented on #1464-1_Maximum_Product_of_Two_Elements_in_an_Array.py
> +        assert type(nums) == list, "The type of nums should be list."
We usually use the assertion statement for a test case. In this case, it is a mechanism for handling run-time errors. So, you should use a raise statement.

2022-11-11 02:25 UTC, nayuta-ai approved these changes

2022-11-11 11:52 UTC, merged