Create #2089_Find_Target_Indices_After_Sorting_Array.py
ashizawaN/LeetCode pull request #6
Opened 2022-10-14 06:40 UTC by ashizawaN

Closes #5

2022-10-14 07:45 UTC, nayuta-ai requested changes

2022-10-14 07:45 UTC, nayuta-ai commented on #2089_Find_Target_Indices_After_Sorting_Array.py
> +        x=[]
x = []

2022-10-14 07:45 UTC, nayuta-ai commented on #2089_Find_Target_Indices_After_Sorting_Array.py
> +            if nums[i]==target:
if nums[i] == target:

2022-10-15 05:53 UTC, ashizawaN commented on #2089_Find_Target_Indices_After_Sorting_Array.py
> +        x=[]
@nayuta-ai 
I wrote "[]" in this code. However, when I type with LeetCode or VSCode, it looks like there is a space.

2022-10-15 12:42 UTC, nayuta-ai requested changes

2022-10-15 12:42 UTC, nayuta-ai commented on #2089_Find_Target_Indices_After_Sorting_Array.py
> +class Solution:
https://github.com/ashizawaN/LeetCode/pull/2/files#r995428337

2022-10-16 09:25 UTC, nayuta-ai approved these changes

2022-10-16 11:13 UTC, merged