create #506-2_Relative_Ranks.py
ashizawaN/LeetCode pull request #71
Opened 2022-11-01 11:35 UTC by ashizawaN

Closes #66 
with sorted()

Please check my code.

2022-11-02 14:34 UTC, nayuta-ai requested changes

2022-11-02 14:34 UTC, nayuta-ai commented on #506-2_Relative_Ranks.py
> +from typing import List
Please write a time complexity and space complexity in the head of the file.
```
# time complexity: O()
# space complexity: O()
```

2022-11-03 03:21 UTC, ashizawaN commented on #506-2_Relative_Ranks.py
> +from typing import List
I've written it. I'll write complexity at the head of line from the next pull request.

2022-11-08 15:36 UTC, nayuta-ai requested changes

2022-11-09 13:15 UTC, nayuta-ai approved these changes

2022-11-10 02:22 UTC, merged