create #938_Range_Sum_of_BST.py
ashizawaN/LeetCode pull request #78
Opened 2022-11-02 04:29 UTC by ashizawaN

Closes #76 

I thought the only way to solve this problem was to use a binary search tree, so I used only one solution method.
Please check my code.

2022-11-02 15:44 UTC, nayuta-ai requested changes

2022-11-02 15:44 UTC, nayuta-ai commented on #938_Range_Sum_of_BST.py
> +        else:
You may want to consider using "early return".

https://zenn.dev/media_engine/articles/early_return

2022-11-03 04:54 UTC, ashizawaN commented on #938_Range_Sum_of_BST.py
> +        else:
I rewrote the code using it. Is this writing correct?

2022-11-08 15:39 UTC, nayuta-ai requested changes

2022-11-08 15:39 UTC, nayuta-ai commented on #938_Range_Sum_of_BST.py
> +    def __init__(self, val=0, left=None, right=None):
Add the type annotation.

2022-11-08 15:39 UTC, nayuta-ai commented on #938_Range_Sum_of_BST.py
> +    def rangeSumBST(self, root: TreeNode, low: int, high: int) -> int:
def rangeSumBST(self, root: Optional[TreeNode], low: int, high: int) -> int:

2022-11-09 13:19 UTC, nayuta-ai approved these changes

2022-11-10 02:27 UTC, merged