create #530_Minimum_Absolute_Difference_in_BST.py
ashizawaN/LeetCode pull request #81
Opened 2022-11-04 15:54 UTC by ashizawaN

Closes #79 

Please check my code. 
I solved it with only one solution because I did not think there was another solution that would change the complexity.

2022-11-05 02:23 UTC, nayuta-ai requested changes

2022-11-05 02:23 UTC, nayuta-ai commented on #530_Minimum_Absolute_Difference_in_BST.py
> +# space complexity: O(1)
The space complexity is O(log n).
A value returned from a recursion method is saved in memory, so the space complexity is O(the height of the recursion). $2^h = n <=> h = log n$.

2022-11-05 02:23 UTC, nayuta-ai commented on #530_Minimum_Absolute_Difference_in_BST.py
> +    def __init__(self, val=0, left=None, right=None):
Write a type annotation.
When an argument use itself type, represent itself type, adding double quotations.
When arguments of a TreeNode have None object, use an Optional class.
```
from typing import Optional

def __init__(self, val: int = 0, left: Optional["TreeNode"] = None, right: Optional["TreeNode"] = None) -> None:
```
[Ref](https://docs.python.org/3/library/typing.html#typing.Optional)

2022-11-06 04:15 UTC, ashizawaN commented on #530_Minimum_Absolute_Difference_in_BST.py
> +# space complexity: O(1)
Thank you for your indication. I've understood it and revised it.

2022-11-07 16:41 UTC, nayuta-ai requested changes

2022-11-07 16:41 UTC, nayuta-ai commented on #530_Minimum_Absolute_Difference_in_BST.py
> +            return min(left, right)
Add a blank line after a return statement of an inner function.

2022-11-09 13:20 UTC, nayuta-ai approved these changes

2022-11-10 03:19 UTC, merged